# Generated by Django 5.1.2 on 2025-04-27 22:44

import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logomarca', models.ImageField(blank=True, help_text='Imagem do brasão oficial (formato recomendado: PNG, dimensões ideais 120x120px ou 150x100px, fundo transparente) para uso no cabeçalho dos relatórios', null=True, upload_to='configuracoes/logomarca/', verbose_name='Logomarca')),
                ('nome_municipio', models.CharField(max_length=100, verbose_name='Nome da Prefeitura')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ da prefeitura')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('telefone_geral', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail institucional')),
                ('site_oficial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Site oficial')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('nome_prefeito', models.CharField(max_length=100, verbose_name='Nome do prefeito(a)')),
                ('nome_vice_prefeito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do vice-prefeito(a)')),
                ('nome_secretario_saude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário municipal da Saúde')),
                ('nome_secretario_educacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário municipal da Educação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Configuração da Prefeitura',
                'verbose_name_plural': 'Configurações da Prefeitura',
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
