# Generated by Django 5.1.2 on 2025-04-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_municipio', models.CharField(max_length=100, verbose_name='Nome oficial do município')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ da prefeitura')),
                ('endereco', models.TextField(help_text='Endereço da prefeitura ou paço municipal', verbose_name='Endereço da sede')),
                ('telefone_geral', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone geral')),
                ('telefone_ouvidoria', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone da ouvidoria')),
                ('telefone_gabinete', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do gabinete')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail institucional')),
                ('site_oficial', models.URLField(blank=True, null=True, verbose_name='Site oficial')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('nome_prefeito', models.CharField(max_length=100, verbose_name='Nome do prefeito(a)')),
                ('nome_vice_prefeito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do vice-prefeito(a)')),
                ('nome_secretario_saude', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário municipal da Saúde')),
                ('nome_secretario_educacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário municipal da Educação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Cliente',
                'verbose_name_plural': 'Configurações do Cliente',
            },
        ),
    ]
