# Generated by Django 5.1.2 on 2025-04-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaocliente',
            name='telefone_gabinete',
        ),
        migrations.RemoveField(
            model_name='configuracaocliente',
            name='telefone_ouvidoria',
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='logomarca',
            field=models.ImageField(blank=True, help_text='Imagem que será usada nos relatórios', null=True, upload_to='configuracoes/logomarca/', verbose_name='Logomarca'),
        ),
        migrations.AlterField(
            model_name='configuracaocliente',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='configuracaocliente',
            name='nome_municipio',
            field=models.CharField(max_length=100, verbose_name='Nome da Prefeitura'),
        ),
        migrations.AlterField(
            model_name='configuracaocliente',
            name='telefone_geral',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
