# Generated by Django 5.1.2 on 2025-04-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_remove_configuracaocliente_telefone_gabinete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocliente',
            name='logomarca',
            field=models.ImageField(blank=True, help_text='Imagem do brasão oficial (formato recomendado: PNG ou JPG, dimensões ideais 300x300px ou 400x300px, fundo transparente)', null=True, upload_to='configuracoes/logomarca/', verbose_name='Logomarca'),
        ),
    ]
