# Generated by Django 5.1.2 on 2025-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_alter_configuracaocliente_logomarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocliente',
            name='logomarca',
            field=models.ImageField(blank=True, help_text='Imagem do brasão oficial (formato recomendado: PNG, dimensões ideais 120x120px ou 150x100px, fundo transparente) para uso no cabeçalho dos relatórios', null=True, upload_to='configuracoes/logomarca/', verbose_name='Logomarca'),
        ),
    ]
