# Generated by Django 5.1.2 on 2025-04-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_alter_configuracaocliente_logomarca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaocliente',
            options={'verbose_name': 'Configuração da Prefeitura', 'verbose_name_plural': 'Configurações da Prefeitura'},
        ),
    ]
