# Generated by Django 5.1.2 on 2025-04-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_alter_configuracaocliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocliente',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='configuracaocliente',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='configuracaocliente',
            name='site_oficial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site oficial'),
        ),
    ]
