# Generated by Django 5.1.2 on 2025-04-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_alter_configuracaocliente_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaocliente',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
    ]
