# Generated by Django 5.1.2 on 2025-02-16 22:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Minhas Mensagens'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(max_length=255, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-timestamp'], name='realtime_ch_room_324403_idx'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
