# Generated by Django 5.1.6 on 2025-02-17 15:29

import realtime.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0006_privatemessage_delete_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('delivered', 'Entregue'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='message',
            field=models.TextField(validators=[realtime.models.validate_message_length], verbose_name='Mensagem'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['delivery_status'], name='realtime_pr_deliver_3338e6_idx'),
        ),
    ]
