# Generated by Django 5.1.6 on 2025-02-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0007_privatemessage_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='privatemessage',
            name='realtime_pr_deliver_3338e6_idx',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='retry_count',
        ),
    ]
