# Generated by Django 5.1.2 on 2025-03-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0009_alter_privatemessage_sender'),
    ]

    operations = [
        # Os campos já existem no modelo, então não precisamos adicioná-los novamente
        # Esta migração é mantida vazia para preservar a história das migrações
    ]
