# Generated by Django 5.1.2 on 2025-03-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0010_privatemessage_deleted_by_recipient_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Como os campos já existem no modelo, mas não estão marcados como migrados,
            # vamos apenas atualizar a tabela de migrações para marcar a migração 0010 como aplicada
            sql="",
            reverse_sql="",
            hints={'force_migrate': True},
        ),
    ]
