# Generated by Django 5.1.6 on 2025-03-24 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0011_fix_duplicate_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='deleted_by_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='has_notification',
            field=models.BooleanField(default=False, verbose_name='Tem notificação'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='realtime.privatemessage', verbose_name='Resposta para'),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='status',
            field=models.CharField(default='active', max_length=10, verbose_name='Status'),
        ),
    ]
