# Generated by Django 5.1.2 on 2025-04-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('escola', '0001_initial'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='profissionais_educacao',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profissao__in': ['educador_especial', 'neuropsicopedagogo', 'pedagogo', 'psicopedagogo', 'assistente_social']}, related_name='escolas_educacao', to='profissionais_app.profissional', verbose_name='Profissionais da Educação'),
        ),
        migrations.AddField(
            model_name='escola',
            name='profissionais_saude',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profissao__in': ['fisioterapeuta', 'fonoaudiologo', 'musicoterapeuta', 'neurologista', 'neuropsicólogo', 'psicologo', 'psiquiatra', 'terapeuta']}, related_name='escolas_saude', to='profissionais_app.profissional', verbose_name='Profissionais da Saúde'),
        ),
        migrations.AddField(
            model_name='modalidadeensino',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='escola',
            name='modalidades',
            field=models.ManyToManyField(blank=True, to='escola.modalidadeensino', verbose_name='Modalidades de Ensino'),
        ),
        migrations.AddField(
            model_name='programaeducacional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='escola',
            name='programas_educacionais',
            field=models.ManyToManyField(blank=True, to='escola.programaeducacional', verbose_name='Programas Educacionais'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='escola',
            name='recursos_disponiveis',
            field=models.ManyToManyField(blank=True, to='escola.recurso', verbose_name='Recursos Disponíveis'),
        ),
    ]
