# Generated by Django 5.1.6 on 2025-04-29 13:25

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='bairro',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='celular',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Digite apenas os números. A formatação será aplicada automaticamente.', validators=[django.core.validators.RegexValidator(message='Formato inválido. Use (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Celular/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cep',
            field=encrypted_model_fields.fields.EncryptedCharField(validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato XXXXX-XXX', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cidade',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='complemento',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='estado',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='numero',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='registro_profissional',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Nº do Registro Profissional'),
        ),
    ]
