# Generated by Django 4.2.9 on 2025-02-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(choices=[('PROFISSIONAIS DA SAÚDE', (('fisioterapeuta', 'Fisioterapeuta'), ('fonoaudiologo', 'Fonoaudiólogo'), ('musicoterapeuta', 'Musicoterapeuta'), ('neurologista', 'Neurologista'), ('neuropsicólogo', 'Neuropsicólogo'), ('psicologo', 'Psicólogo Clínico'), ('psiquiatra', 'Psiquiatra'), ('terapeuta', 'Terapeuta Ocupacional'))), ('PROFISSIONAIS DA EDUCAÇÃO', (('assistente_social', 'Assistente Social'), ('educador_especial', 'Educador Especial (AEE)'), ('neuropsicopedagogo', 'Neuropsicopedagogo'), ('pedagogo', 'Pedagogo'), ('psicopedagogo', 'Psicopedagogo')))], max_length=50, verbose_name='Profissão'),
        ),
    ]
