# Generated by Django 5.1.2 on 2025-04-16 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0002_alter_profissional_profissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='celular',
            field=models.CharField(help_text='Digite apenas os números. A formatação será aplicada automaticamente.', max_length=15, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')], verbose_name='Celular/WhatsApp'),
        ),
    ]
