# Generated by Django 5.1.6 on 2025-04-29 21:33

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0002_alter_profissional_bairro_alter_profissional_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='local_registro',
        ),
        migrations.AddField(
            model_name='profissional',
            name='estado_registro',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado de Registro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='bairro',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cep',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='CEP inválido. Use o formato XXXXX-XXX', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cidade',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='complemento',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='endereco',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='estado',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='numero',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
