# Generated by Django 5.1.2 on 2025-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0003_alter_profissional_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='profissao',
            field=models.CharField(blank=True, choices=[('', '---------'), ('PROFISSIONAIS DA SAÚDE', [('fisioterapeuta', 'Fisioterapeuta'), ('fonoaudiologo', 'Fonoaudiólogo'), ('musicoterapeuta', 'Musicoterapeuta'), ('neurologista', 'Neurologista'), ('neuropsicólogo', 'Neuropsicólogo'), ('psicologo', 'Psicólogo Clínico'), ('psiquiatra', 'Psiquiatra'), ('terapeuta', 'Terapeuta Ocupacional')]), ('PROFISSIONAIS DA EDUCAÇÃO', [('assistente_social', 'Assistente Social'), ('educador_especial', 'Educador Especial (AEE)'), ('neuropsicopedagogo', 'Neuropsicopedagogo'), ('pedagogo', 'Pedagogo'), ('psicopedagogo', 'Psicopedagogo')])], max_length=50, verbose_name='Profissão'),
        ),
    ]
