# Generated by Django 5.1.2 on 2024-12-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicaoneurodivergente',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Condição Aluno/Paciente', 'verbose_name_plural': 'Condições Alunos/Pacientes'},
        ),
    ]
