# Generated by Django 5.1.2 on 2025-04-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '__first__'),
        ('escola', '0002_initial'),
        ('neurodivergentes', '0001_initial'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptacaocurricular',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__startswith': 'educador_especial'}, on_delete=django.db.models.deletion.PROTECT, related_name='adaptacoes_curriculares', to='profissionais_app.profissional'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamneses_responsavel', to='profissionais_app.profissional', verbose_name='Profissional Responsável'),
        ),
        migrations.AddField(
            model_name='categorianeurodivergente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='condicaoneurodivergente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicoes', to='neurodivergentes.categorianeurodivergente', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='condicaoneurodivergente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='diagnosticoneurodivergente',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='neurodivergentes.categorianeurodivergente'),
        ),
        migrations.AddField(
            model_name='diagnosticoneurodivergente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='diagnosticoneurodivergente',
            name='condicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='neurodivergentes.condicaoneurodivergente', verbose_name='Neurodivergência'),
        ),
        migrations.AddField(
            model_name='historicoescolar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='historicoescolar',
            name='escola_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_neurodivergentes', to='escola.escola'),
        ),
        migrations.AddField(
            model_name='medicacao',
            name='anamnese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacoes', to='neurodivergentes.anamnese'),
        ),
        migrations.AddField(
            model_name='medicacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='metahabilidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='pedagogo_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'profissao__in': ['assistente_social', 'educador_especial', 'neuropsicopedagogo', 'pedagogo', 'psicopedagogo']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoramentos', to='profissionais_app.profissional', verbose_name='Profissional Responosável'),
        ),
        migrations.AddField(
            model_name='monitoramentometa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='monitoramentometa',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramento_metas', to='neurodivergentes.metahabilidade'),
        ),
        migrations.AddField(
            model_name='monitoramentometa',
            name='monitoramento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramento_metas', to='neurodivergentes.monitoramento'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='metas',
            field=models.ManyToManyField(help_text='Selecione uma ou mais metas/habilidades para este planejamento', through='neurodivergentes.MonitoramentoMeta', to='neurodivergentes.metahabilidade', verbose_name='Metas/Habilidades'),
        ),
        migrations.AddField(
            model_name='neurodivergencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='diagnosticoneurodivergente',
            name='neurodivergencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='neurodivergentes.neurodivergencia'),
        ),
        migrations.AddField(
            model_name='neurodivergente',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='escola.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='neurodivergencia',
            name='neurodivergente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neurodivergencias', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='historicoescolar',
            name='neurodivergente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_escolar', to='neurodivergentes.neurodivergente'),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='neurodivergente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_familiar', to='neurodivergentes.neurodivergente'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='neurodivergente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pareceres', to='escola.escola'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'profissao__in': ['educador_especial', 'pedagogo', 'psicopedagogo', 'neuropsicopedagogo']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_responsavel', to='profissionais_app.profissional', verbose_name='Profissional Responsável'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='pedagogo_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__in': ['educador_especial', 'pedagogo', 'psicopedagogo', 'neuropsicopedagogo']}, on_delete=django.db.models.deletion.PROTECT, related_name='pdis_responsavel', to='profissionais_app.profissional', verbose_name='Pedagogo Responsável'),
        ),
        migrations.AddField(
            model_name='pdimetahabilidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='pdimetahabilidade',
            name='meta_habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='neurodivergentes.metahabilidade', verbose_name='Meta/Habilidade'),
        ),
        migrations.AddField(
            model_name='pdimetahabilidade',
            name='pdi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_habilidades', to='neurodivergentes.pdi'),
        ),
        migrations.AddField(
            model_name='planoeducacional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='planoeducacional',
            name='pdi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano_educacional', to='neurodivergentes.pdi', verbose_name='PDI'),
        ),
        migrations.AddField(
            model_name='planoeducacional',
            name='pedagogo_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__startswith': 'pedagogo'}, on_delete=django.db.models.deletion.PROTECT, related_name='planos_educacionais', to='profissionais_app.profissional'),
        ),
        migrations.AddField(
            model_name='adaptacaocurricular',
            name='plano_educacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptacoes', to='neurodivergentes.planoeducacional'),
        ),
        migrations.AddField(
            model_name='registroevolucao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='registroevolucao',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_evolucao', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
        migrations.AddField(
            model_name='registroevolucao',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_evolucao', to='profissionais_app.profissional'),
        ),
        migrations.AddField(
            model_name='rotinaatividade',
            name='anamnese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas', to='neurodivergentes.anamnese'),
        ),
        migrations.AddField(
            model_name='rotinaatividade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='seriescursadas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='neurodivergente',
            name='ano_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='neurodivergentes.seriescursadas', verbose_name='Ano Escolar'),
        ),
        migrations.AddField(
            model_name='historicoescolar',
            name='series_cursadas',
            field=models.ManyToManyField(blank=True, help_text='Selecione todas as séries já cursadas na rede municipal', related_name='historicos', to='neurodivergentes.seriescursadas', verbose_name='Séries Cursadas'),
        ),
        migrations.AlterUniqueTogether(
            name='condicaoneurodivergente',
            unique_together={('categoria', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='monitoramentometa',
            unique_together={('monitoramento', 'meta')},
        ),
        migrations.AlterUniqueTogether(
            name='monitoramento',
            unique_together={('neurodivergente', 'mes', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='pdimetahabilidade',
            unique_together={('pdi', 'meta_habilidade')},
        ),
    ]
