# Generated by Django 4.2.9 on 2025-02-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pareceravaliativo',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Aluno/Paciente', 'verbose_name_plural': 'Alunos/Pacientes'},
        ),
    ]
