# Generated by Django 5.1.2 on 2024-12-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0002_alter_condicaoneurodivergente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='especialidade_medica',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='primeira_aprendizagem',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='rel_colegas',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='rel_mae',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='rel_pai',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='rel_professores',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='rel_social',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='segunda_aprendizagem',
        ),
        migrations.RemoveField(
            model_name='anamnese',
            name='terceira_aprendizagem',
        ),
    ]
