# Generated by Django 4.2.9 on 2025-02-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0002_alter_pareceravaliativo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pareceravaliativo',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.AlterField(
            model_name='pareceravaliativo',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
    ]
