# Generated by Django 5.1.2 on 2024-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0003_remove_anamnese_especialidade_medica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='comportamento_familiar',
            field=models.TextField(default='A ser preenchido', verbose_name='Comportamento no Ambiente Meio Familiar'),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='comportamento_social',
            field=models.TextField(default='A ser preenchido', verbose_name='Comportamento no Ambiente Social e Escolar'),
        ),
    ]
