# Generated by Django 4.2.9 on 2025-02-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0003_alter_pareceravaliativo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pareceravaliativo',
            name='conclusoes',
        ),
        migrations.RemoveField(
            model_name='pareceravaliativo',
            name='desafios',
        ),
        migrations.RemoveField(
            model_name='pareceravaliativo',
            name='pontos_fortes',
        ),
        migrations.RemoveField(
            model_name='pareceravaliativo',
            name='recomendacoes',
        ),
    ]
