# Generated by Django 5.1.6 on 2025-04-29 14:27

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0003_alter_anamnese_aspectos_cognitivos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroevolucao',
            name='descricao',
            field=encrypted_model_fields.fields.EncryptedTextField(verbose_name='Descrição da Evolução'),
        ),
    ]
