# Generated by Django 5.1.2 on 2024-12-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0004_anamnese_comportamento_familiar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='comportamento_familiar',
            field=models.TextField(default='A ser preenchido', verbose_name='Comportamento no Meio Familiar'),
        ),
    ]
