# Generated by Django 4.2.9 on 2025-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0004_remove_pareceravaliativo_conclusoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareceravaliativo',
            name='evolucao',
            field=models.TextField(verbose_name='Parecer Descritivo'),
        ),
    ]
