# Generated by Django 5.1.2 on 2024-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0005_alter_anamnese_comportamento_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='comportamento_familiar',
            field=models.TextField(default='A ser preenchido', verbose_name='Comportamento no Ambiente Familiar'),
        ),
    ]
