# Generated by Django 4.2.9 on 2025-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0005_alter_pareceravaliativo_evolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareceravaliativo',
            name='data_avaliacao',
            field=models.DateField(verbose_name='Data do Parecer'),
        ),
    ]
