# Generated by Django 5.1.6 on 2025-04-29 14:31

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0005_alter_adaptacaocurricular_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='observacoes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Descreva o planejamento para esta meta/habilidade', null=True, verbose_name='Planejamento'),
        ),
    ]
