# Generated by Django 5.1.6 on 2025-04-29 14:32

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0006_alter_monitoramento_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareceravaliativo',
            name='evolucao',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True, verbose_name='Parecer Descritivo'),
        ),
    ]
