# Generated by Django 5.1.2 on 2024-12-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0006_alter_anamnese_comportamento_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='neurodivergente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
    ]
