# Generated by Django 4.2.9 on 2025-02-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais_app', '0002_alter_profissional_profissao'),
        ('neurodivergentes', '0006_alter_pareceravaliativo_data_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareceravaliativo',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'profissao__in': ['educador_especial', 'pedagogo', 'psicopedagogo', 'neuropsicopedagogo']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pareceres_responsavel', to='profissionais_app.profissional', verbose_name='Profissional Responsável'),
        ),
    ]
