# Generated by Django 5.1.2 on 2025-03-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0007_pareceravaliativo_profissional_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='anexos',
            field=models.FileField(blank=True, null=True, upload_to='neurodivergentes/anamnese/', verbose_name='Anexos'),
        ),
        migrations.AlterField(
            model_name='diagnosticoneurodivergente',
            name='condicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='neurodivergentes.condicaoneurodivergente', verbose_name='Neurodivergência'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=3, help_text='Selecione o mês do PEI', verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='neurodivergencia',
            name='neurodivergente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='neurodivergencias', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
    ]
