# Generated by Django 5.1.6 on 2025-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_email_secretario_educacao_and_more'),
        ('neurodivergentes', '0007_alter_pareceravaliativo_evolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=5, help_text='Selecione o mês do PEI', verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='seriescursadas',
            name='nome',
            field=models.CharField(choices=[('bercario1', 'Berçário I'), ('bercario2', 'Berçário II'), ('maternal', 'Maternal'), ('jardim', 'Jardim'), ('pre1', 'Pré I'), ('pre2', 'Pré II'), ('1ano', '1º Ano'), ('2ano', '2º Ano'), ('3ano', '3º Ano'), ('4ano', '4º Ano'), ('5ano', '5º Ano'), ('6ano', '6º Ano'), ('7ano', '7º Ano'), ('8ano', '8º Ano'), ('9ano', '9º Ano')], max_length=10, verbose_name='Série'),
        ),
        migrations.AlterUniqueTogether(
            name='seriescursadas',
            unique_together={('cliente', 'nome')},
        ),
    ]
