# Generated by Django 5.1.6 on 2025-03-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0008_anamnese_anexos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neurodivergente',
            options={'ordering': ['primeiro_nome', 'ultimo_nome'], 'verbose_name': 'Aluno/Paciente', 'verbose_name_plural': 'Alunos/Pacientes'},
        ),
    ]
