# Generated by Django 5.1.2 on 2024-12-12 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0008_alter_pdi_neurodivergente'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamnese',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anamneses_responsavel', to='profissionais_app.profissional', verbose_name='Profissional Responsável'),
        ),
    ]
