# Generated by Django 5.1.6 on 2025-04-07 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0009_alter_neurodivergente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorianeurodivergente',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Categoria CID-10', 'verbose_name_plural': 'Categorias CID-10'},
        ),
        migrations.AlterModelOptions(
            name='condicaoneurodivergente',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Condição CID-10', 'verbose_name_plural': 'Condições CID-10'},
        ),
        migrations.AlterModelOptions(
            name='neurodivergencia',
            options={'verbose_name': 'Neurodivergente', 'verbose_name_plural': 'Neurodivergentes'},
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='mes',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=4, help_text='Selecione o mês do PEI', verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='registroevolucao',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_evolucao', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
    ]
