# Generated by Django 5.1.2 on 2024-12-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0009_anamnese_profissional_responsavel'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='pedagogo_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__in': ['pedagogo', 'psicopedagogo', 'neuropsicopedagogo']}, on_delete=django.db.models.deletion.PROTECT, related_name='pdis_responsavel', to='profissionais_app.profissional', verbose_name='Pedagogo Responsável'),
        ),
    ]
