# Generated by Django 5.1.2 on 2024-12-13 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0010_alter_pdi_pedagogo_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='tempo_prematuridade',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Tempo de Prematuridade (semanas)'),
        ),
    ]
