# Generated by Django 5.1.2 on 2025-04-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0010_alter_categorianeurodivergente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pareceravaliativo',
            name='evolucao',
            field=models.TextField(blank=True, null=True, verbose_name='Parecer Descritivo'),
        ),
    ]
