# Generated by Django 5.1.6 on 2025-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0011_alter_pareceravaliativo_evolucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pareceravaliativo',
            name='grafico_data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final do Gráfico'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='grafico_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Inicial do Gráfico'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='grafico_frequencia',
            field=models.ImageField(blank=True, null=True, upload_to='neurodivergentes/pareceres/graficos/', verbose_name='Gráfico de Frequência'),
        ),
        migrations.AddField(
            model_name='pareceravaliativo',
            name='grafico_monitoramento',
            field=models.ImageField(blank=True, null=True, upload_to='neurodivergentes/pareceres/graficos/', verbose_name='Gráfico de Monitoramento'),
        ),
    ]
