# Generated by Django 5.1.2 on 2024-12-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0011_alter_anamnese_tempo_prematuridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='comportamento_familiar',
            field=models.TextField(blank=True, verbose_name='Comportamento no Ambiente Familiar'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='comportamento_social',
            field=models.TextField(blank=True, verbose_name='Comportamento no Ambiente Social e Escolar'),
        ),
    ]
