# Generated by Django 5.1.6 on 2025-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0012_pareceravaliativo_grafico_data_fim_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='pareceravaliativo',
        #     name='grafico_frequencia',
        #     field=models.ImageField(blank=True, null=True, upload_to='neurodivergentes/pareceres/graficos/', verbose_name='Gráfico de Frequência'),
        # ),
        # migrations.AddField(
        #     model_name='pareceravaliativo',
        #     name='grafico_monitoramento',
        #     field=models.ImageField(blank=True, null=True, upload_to='neurodivergentes/pareceres/graficos/', verbose_name='Gráfico de Monitoramento'),
        # ),
    ]
