# Generated by Django 5.1.2 on 2024-12-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0012_alter_anamnese_comportamento_familiar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planoeducacional',
            options={'verbose_name': 'ACI', 'verbose_name_plural': 'ACIs'},
        ),
    ]
