# Generated by Django 5.1.2 on 2025-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0013_add_grafico_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='status',
            field=models.CharField(choices=[('ausente', 'Ausente'), ('iniciado', 'Iniciado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20, verbose_name='Status'),
        ),
    ]
