# Generated by Django 5.1.2 on 2024-12-14 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0013_alter_planoeducacional_options'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoeducacional',
            name='pedagogo_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__startswith': 'pedagogo'}, on_delete=django.db.models.deletion.PROTECT, related_name='planos_educacionais', to='profissionais_app.profissional'),
        ),
    ]
