# Generated by Django 5.1.2 on 2024-12-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0014_alter_planoeducacional_pedagogo_responsavel'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptacaocurricular',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__startswith': 'pedadogo'}, on_delete=django.db.models.deletion.PROTECT, related_name='adaptacoes_curriculares', to='profissionais_app.profissional'),
        ),
    ]
