# Generated by Django 5.1.2 on 2024-12-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0015_alter_adaptacaocurricular_professor_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptacaocurricular',
            old_name='professor_responsavel',
            new_name='pedagogo_responsavel',
        ),
    ]
