# Generated by Django 5.1.6 on 2025-04-17 18:33

import django.db.models.deletion
import neurodivergentes.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0015_neurodivergente_ano_escolar_neurodivergente_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-ano', '-mes'], 'verbose_name': 'PAEE', 'verbose_name_plural': 'PAEE'},
        ),
        migrations.AlterModelOptions(
            name='registroevolucao',
            options={'ordering': ['-data', '-created_at'], 'verbose_name': 'Histórico de Evolução', 'verbose_name_plural': 'Histórico de Evolução'},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticoneurodivergente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[neurodivergentes.models.base.validate_future_date], verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='neurodivergente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_familiar', to='neurodivergentes.neurodivergente'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupação'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('pai_mae', 'Pai/Mãe'), ('filho', 'Filho(a)'), ('irmao', 'Irmão(ã)'), ('avo', 'Avô/Avó'), ('tio', 'Tio(a)'), ('sobrinho', 'Sobrinho(a)'), ('primo', 'Primo(a)'), ('conjuge', 'Cônjuge'), ('companheiro', 'Companheiro(a)'), ('padrasto', 'Padrasto/Madrasta'), ('enteado', 'Enteado(a)'), ('cunhado', 'Cunhado(a)'), ('genro', 'Genro/Nora'), ('sogro', 'Sogro(a)'), ('tutor', 'Tutor(a)'), ('cuidador', 'Cuidador(a)'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Vínculo/Parentesco'),
        ),
    ]
