# Generated by Django 5.1.2 on 2024-12-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0016_rename_professor_responsavel_adaptacaocurricular_pedagogo_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptacaocurricular',
            old_name='pedagogo_responsavel',
            new_name='professor_responsavel',
        ),
    ]
