# Generated by Django 5.1.2 on 2025-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0016_alter_monitoramento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoneurodivergente',
            name='data_identificacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Identificação'),
        ),
        migrations.AlterField(
            model_name='grupofamiliar',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pai_mae', 'Pai/Mãe'), ('filho', 'Filho(a)'), ('irmao', 'Irmão(ã)'), ('avo', 'Avô/Avó'), ('tio', 'Tio(a)'), ('sobrinho', 'Sobrinho(a)'), ('primo', 'Primo(a)'), ('conjuge', 'Cônjuge'), ('companheiro', 'Companheiro(a)'), ('padrasto', 'Padrasto/Madrasta'), ('enteado', 'Enteado(a)'), ('cunhado', 'Cunhado(a)'), ('genro', 'Genro/Nora'), ('sogro', 'Sogro(a)'), ('tutor', 'Tutor(a)'), ('cuidador', 'Cuidador(a)'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Vínculo/Parentesco'),
        ),
    ]
