# Generated by Django 5.1.2 on 2025-04-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0017_alter_diagnosticoneurodivergente_data_identificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurodivergente',
            name='cor_pele',
            field=models.CharField(blank=True, choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('amarela', 'Amarela'), ('indigena', 'Indígena')], max_length=10, verbose_name='Cor da Pele'),
        ),
        migrations.AddField(
            model_name='neurodivergente',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('brasileira', 'Brasileira'), ('estrangeira', 'Estrangeira')], max_length=20, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='neurodivergente',
            name='pais_origem',
            field=models.CharField(blank=True, max_length=50, verbose_name='País de Origem'),
        ),
    ]
