# Generated by Django 5.1.2 on 2024-12-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0017_rename_pedagogo_responsavel_adaptacaocurricular_professor_responsavel'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptacaocurricular',
            name='professor_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__startswith': 'educador_especial'}, on_delete=django.db.models.deletion.PROTECT, related_name='adaptacoes_curriculares', to='profissionais_app.profissional'),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='pedagogo_responsavel',
            field=models.ForeignKey(limit_choices_to={'profissao__in': ['educador_especial', 'pedagogo', 'psicopedagogo', 'neuropsicopedagogo']}, on_delete=django.db.models.deletion.PROTECT, related_name='pdis_responsavel', to='profissionais_app.profissional', verbose_name='Pedagogo Responsável'),
        ),
    ]
