# Generated by Django 5.1.2 on 2025-02-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0018_alter_adaptacaocurricular_professor_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pareceravaliativo',
            options={'ordering': ['-data_avaliacao'], 'verbose_name': 'Parecer', 'verbose_name_plural': 'Pareceres'},
        ),
        migrations.AlterModelOptions(
            name='registroevolucao',
            options={'ordering': ['-data', '-created_at'], 'verbose_name': 'Evolução', 'verbose_name_plural': 'Evolução'},
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
    ]
