# Generated by Django 5.1.2 on 2025-04-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0018_neurodivergente_cor_pele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neurodivergente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
    ]
