# Generated by Django 5.1.2 on 2025-02-10 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0019_alter_pareceravaliativo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoramento',
            options={'ordering': ['-mes_ano'], 'verbose_name': 'PEI', 'verbose_name_plural': 'PEI'},
        ),
        migrations.AddField(
            model_name='monitoramento',
            name='mes_ano',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 18, 38, 12, 572171, tzinfo=datetime.timezone.utc), help_text='Selecione o mês e ano do PEI', verbose_name='Mês/Ano'),
        ),
    ]
