# Generated by Django 5.1.2 on 2025-02-10 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0021_copy_data_to_mes_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoramento',
            name='data',
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='mes_ano',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 18, 38, 35, 751285, tzinfo=datetime.timezone.utc), help_text='Selecione o mês e ano do PEI', verbose_name='Mês/Ano'),
        ),
    ]
