# Generated by Django 5.1.2 on 2025-02-10 18:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0022_remove_data_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoramento',
            name='mes_ano',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 18, 40, 45, 770773, tzinfo=datetime.timezone.utc), help_text='Selecione o mês e ano do PEI', verbose_name='Mês/Ano'),
        ),
        migrations.AlterField(
            model_name='monitoramento',
            name='neurodivergente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente'),
        ),
    ]
