# Generated by Django 5.1.2 on 2025-02-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0030_monitoramento_metas'),
    ]

    operations = [
        migrations.RunSQL(
            """
            SET FOREIGN_KEY_CHECKS=0;
            ALTER TABLE neurodivergentes_monitoramento DROP FOREIGN KEY IF EXISTS fk_meta_habilidade;
            ALTER TABLE neurodivergentes_monitoramento DROP COLUMN IF EXISTS meta_id;
            SET FOREIGN_KEY_CHECKS=1;
            """,
            "SELECT 1;"
        ),
    ]
