# Generated by Django 5.1.2 on 2025-02-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neurodivergentes', '0031_remove_monitoramento_mes_ano_monitoramento_ano_and_more'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoramento',
            name='pedagogo_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'pedagogo'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='monitoramentos', to='profissionais_app.profissional', verbose_name='Pedagogo Responsável'),
        ),
    ]
