# Generated by Django 5.1.2 on 2025-02-14 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escola', '0001_initial'),
        ('neurodivergentes', '0007_pareceravaliativo_profissional_responsavel'),
        ('profissionais_app', '0002_alter_profissional_profissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNCCDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina BNCC',
                'verbose_name_plural': 'Disciplinas BNCC',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AdaptacaoCurricularIndividualizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data do Cadastro')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neurodivergentes.neurodivergente', verbose_name='Aluno/Paciente')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escola.escola')),
                ('profissional_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais_app.profissional')),
            ],
            options={
                'verbose_name': 'Adaptação Curricular Individualizada',
                'verbose_name_plural': 'Adaptações Curriculares Individualizadas',
                'ordering': ['-data_cadastro', 'aluno'],
            },
        ),
        migrations.CreateModel(
            name='BNCCHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_conhecimento', models.TextField(verbose_name='Objetos do Conhecimento')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.TextField(verbose_name='Descrição da Habilidade')),
                ('ano', models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano'), ('5', '5º Ano'), ('6', '6º Ano'), ('7', '7º Ano'), ('8', '8º Ano'), ('9', '9º Ano')], max_length=1, verbose_name='Ano')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], max_length=1, verbose_name='Trimestre')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='adaptacao_curricular.bnccdisciplina')),
            ],
            options={
                'verbose_name': 'Habilidade BNCC',
                'verbose_name_plural': 'Habilidades BNCC',
                'ordering': ['disciplina', 'ano', 'trimestre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AdaptacaoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritivo_adaptacao', models.TextField(verbose_name='Descritivo da Adaptação Curricular')),
                ('aci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptacoes', to='adaptacao_curricular.adaptacaocurricularindividualizada')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptacao_curricular.bncchabilidade')),
            ],
            options={
                'verbose_name': 'Adaptação de Habilidade',
                'verbose_name_plural': 'Adaptações de Habilidades',
                'ordering': ['aci', 'habilidade'],
            },
        ),
    ]
