# Generated by Django 5.1.2 on 2025-04-27 22:44

import django_multitenant.mixins
import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptacaoCurricularIndividualizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade_ensino', models.CharField(choices=[('EI', 'Educação Infantil'), ('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio')], default='EF', max_length=2, verbose_name='Modalidade de Ensino')),
                ('ano', models.CharField(choices=[('Educação Infantil', [('B1', 'Berçário I'), ('B2', 'Berçário II'), ('M1', 'Maternal I'), ('M2', 'Maternal II'), ('P1', 'Pré I'), ('P2', 'Pré II')]), ('Ensino Fundamental', [('1F', '1.º ano'), ('2F', '2.º ano'), ('3F', '3.º ano'), ('4F', '4.º ano'), ('5F', '5.º ano'), ('6F', '6.º ano'), ('7F', '7.º ano'), ('8F', '8.º ano'), ('9F', '9.º ano')]), ('Ensino Médio', [('1M', '1.º ano'), ('2M', '2.º ano'), ('3M', '3.º ano')])], default='1F', max_length=2, verbose_name='Ano Escolar')),
                ('trimestre', models.CharField(choices=[('1', '1.º trimestre'), ('2', '2.º trimestre'), ('3', '3.º trimestre'), ('S1', '1.º Semestre'), ('S2', '2.º Semestre')], default='1', max_length=2, verbose_name='Trimestre')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data do Cadastro')),
            ],
            options={
                'verbose_name': 'PEI',
                'verbose_name_plural': 'PEIs',
                'ordering': ['-data_cadastro', 'aluno'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdaptacaoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descritivo_adaptacao', models.TextField(verbose_name='Descritivo da Adaptação Curricular')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['aci', 'habilidade'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='BNCCDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina BNCC',
                'verbose_name_plural': 'Disciplinas BNCC',
                'ordering': ['nome'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.CreateModel(
            name='BNCCHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('objeto_conhecimento', models.TextField(verbose_name='Objetos do Conhecimento')),
                ('descricao', models.TextField(verbose_name='Descrição da Habilidade')),
                ('ano', models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano'), ('5', '5º Ano'), ('6', '6º Ano'), ('7', '7º Ano'), ('8', '8º Ano'), ('9', '9º Ano')], max_length=1, verbose_name='Ano')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre')], max_length=1, verbose_name='Trimestre')),
            ],
            options={
                'verbose_name': 'Código BNCC',
                'verbose_name_plural': 'Códigos BNCC',
                'ordering': ['disciplina', 'ano', 'trimestre', 'codigo'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
