# Generated by Django 5.1.2 on 2025-02-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptacaohabilidade',
            options={'ordering': ['aci', 'habilidade'], 'verbose_name': 'Habilidade', 'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='bncchabilidade',
            options={'ordering': ['disciplina', 'ano', 'trimestre', 'codigo'], 'verbose_name': 'Cadastro BNCC', 'verbose_name_plural': 'Cadastros BNCC'},
        ),
        migrations.AlterField(
            model_name='bncchabilidade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='adaptacao_curricular.bnccdisciplina', verbose_name='Disciplina'),
        ),
    ]
