# Generated by Django 5.1.2 on 2025-04-27 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adaptacao_curricular', '0002_initial'),
        ('clientes', '__first__'),
        ('profissionais_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptacaocurricularindividualizada',
            name='profissional_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais_app.profissional'),
        ),
        migrations.AddField(
            model_name='adaptacaohabilidade',
            name='aci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptacoes', to='adaptacao_curricular.adaptacaocurricularindividualizada'),
        ),
        migrations.AddField(
            model_name='adaptacaohabilidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='bnccdisciplina',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='bncchabilidade',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='bncchabilidade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='adaptacao_curricular.bnccdisciplina', verbose_name='Disciplina:'),
        ),
        migrations.AddField(
            model_name='adaptacaohabilidade',
            name='habilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adaptacao_curricular.bncchabilidade'),
        ),
    ]
