# Generated by Django 5.1.2 on 2025-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0002_alter_adaptacaohabilidade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptacaocurricularindividualizada',
            name='ano',
            field=models.CharField(choices=[('B1', 'Berçário I'), ('B2', 'Berçário II'), ('M1', 'Maternal I'), ('M2', 'Maternal II'), ('P1', 'Pré I'), ('P2', 'Pré II'), ('1F', '1.º ano'), ('2F', '2.º ano'), ('3F', '3.º ano'), ('4F', '4.º ano'), ('5F', '5.º ano'), ('6F', '6.º ano'), ('7F', '7.º ano'), ('8F', '8.º ano'), ('9F', '9.º ano'), ('1M', '1.º ano'), ('2M', '2.º ano'), ('3M', '3.º ano')], default='1F', max_length=2, verbose_name='Ano'),
        ),
        migrations.AddField(
            model_name='adaptacaocurricularindividualizada',
            name='modalidade_ensino',
            field=models.CharField(choices=[('EI', 'Educação Infantil'), ('EF', 'Ensino Fundamental'), ('EM', 'Ensino Médio')], default='EF', max_length=2, verbose_name='Modalidade de Ensino'),
        ),
        migrations.AddField(
            model_name='adaptacaocurricularindividualizada',
            name='trimestre',
            field=models.CharField(choices=[('1', '1.º trimestre'), ('2', '2.º trimestre'), ('3', '3.º trimestre')], default='1', max_length=1, verbose_name='Trimestre'),
        ),
    ]
