# Generated by Django 5.1.2 on 2025-02-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0003_adaptacaocurricularindividualizada_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptacaocurricularindividualizada',
            name='ano',
            field=models.CharField(choices=[('Educação Infantil', [('B1', 'Berçário I'), ('B2', 'Berçário II'), ('M1', 'Maternal I'), ('M2', 'Maternal II'), ('P1', 'Pré I'), ('P2', 'Pré II')]), ('Ensino Fundamental', [('1F', '1.º ano'), ('2F', '2.º ano'), ('3F', '3.º ano'), ('4F', '4.º ano'), ('5F', '5.º ano'), ('6F', '6.º ano'), ('7F', '7.º ano'), ('8F', '8.º ano'), ('9F', '9.º ano')]), ('Ensino Médio', [('1M', '1.º ano'), ('2M', '2.º ano'), ('3M', '3.º ano')])], default='1F', max_length=2, verbose_name='Ano Escolar'),
        ),
    ]
