# Generated by Django 5.1.6 on 2025-04-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0004_alter_adaptacaocurricularindividualizada_ano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptacaocurricularindividualizada',
            options={'ordering': ['-data_cadastro', 'aluno'], 'verbose_name': 'ACI', 'verbose_name_plural': 'ACIs'},
        ),
        migrations.AlterModelOptions(
            name='bncchabilidade',
            options={'ordering': ['disciplina', 'ano', 'trimestre', 'codigo'], 'verbose_name': 'Código BNCC', 'verbose_name_plural': 'Códigos BNCC'},
        ),
    ]
