# Generated by Django 5.1.2 on 2025-04-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0005_alter_adaptacaocurricularindividualizada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bncchabilidade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='adaptacao_curricular.bnccdisciplina', verbose_name='Disciplina:'),
        ),
    ]
