# Generated by Django 5.1.2 on 2025-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0006_alter_bncchabilidade_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptacaocurricularindividualizada',
            name='trimestre',
            field=models.CharField(choices=[('1', '1.º trimestre'), ('2', '2.º trimestre'), ('3', '3.º trimestre'), ('S1', '1.º Semestre'), ('S2', '2.º Semestre')], default='1', max_length=2, verbose_name='Trimestre'),
        ),
    ]
