# Generated by Django 5.1.2 on 2025-04-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adaptacao_curricular', '0007_alter_adaptacaocurricularindividualizada_trimestre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adaptacaocurricularindividualizada',
            options={'ordering': ['-data_cadastro', 'aluno'], 'verbose_name': 'PEI', 'verbose_name_plural': 'PEIs'},
        ),
    ]
