# Generated by Django 5.1.2 on 2025-04-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dominio',
        ),
    ]
