# Generated by Django 5.1.2 on 2025-04-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_dominio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente/Prefeitura', 'verbose_name_plural': 'Clientes/Prefeituras'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo_responsavel_financeiro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo do Responsável Financeiro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_atualizacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Atualização'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_principal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_responsavel_financeiro',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável Financeiro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='Geralmente isento para prefeituras', max_length=20, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_responsavel_financeiro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Responsável Financeiro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_alunos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número Aproximado de Alunos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_escolas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Escolas Municipais'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_habitantes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Habitantes'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_responsavel_financeiro',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Responsável Financeiro'),
        ),
    ]
