# Generated by Django 5.1.6 on 2025-04-29 13:50

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options_cliente_ativo_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email_secretario_educacao',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, verbose_name='E-mail Secretário de Educação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_secretario_saude',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, verbose_name='E-mail Secretário de Saúde'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_prefeito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Prefeito(a)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_secretario_educacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário de Educação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_secretario_saude',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Secretário de Saúde'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_vice_prefeito',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Vice-Prefeito(a)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_secretario_educacao',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Telefone Secretário de Educação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone_secretario_saude',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Telefone Secretário de Saúde'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email_responsavel_financeiro',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True, verbose_name='E-mail do Responsável Financeiro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone_responsavel_financeiro',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Telefone do Responsável Financeiro'),
        ),
    ]
